set autocommit = off;
start transaction;

insert into misto_prace (obec, ulice, cislo_popisne, katastralni_uzemi) values ('Kubangkondang', 'Village Green', 69466, '303658');
insert into misto_prace (obec, ulice, cislo_popisne, katastralni_uzemi) values ('Timashëvsk', 'Novick', 88875, '519859');
insert into misto_prace (obec, ulice, cislo_popisne, katastralni_uzemi) values ('Dębowa Łąka', 'Dovetail', 90369, '803237');
insert into misto_prace (obec, ulice, cislo_popisne, katastralni_uzemi) values ('Popovo', 'Kingsford', 46114, '374550');
insert into misto_prace (obec, ulice, cislo_popisne, katastralni_uzemi) values ('Keratéa', 'Farmco', 15757, '768604');
insert into misto_prace (obec, ulice, cislo_popisne, katastralni_uzemi) values ('Novhorod-Sivers’kyy', 'Mallory', 13727, '722329');
insert into misto_prace (obec, ulice, cislo_popisne, katastralni_uzemi) values ('Hushi', 'Roth', 70318, 762228);
insert into misto_prace (obec, ulice, cislo_popisne, katastralni_uzemi) values ('Huayacundo Arma', 'Tennessee', 68217, '401341');
insert into misto_prace (obec, ulice, cislo_popisne, katastralni_uzemi) values ('Miguelópolis', 'Bartillon', 8381, '729607');
insert into misto_prace (obec, ulice, cislo_popisne, katastralni_uzemi) values ('Al Jawādīyah', 'Melody', 52091, '724576');
insert into misto_prace (obec, ulice, cislo_popisne, katastralni_uzemi) values ('Ardee', 'Petterle', 99873, '525189');
insert into misto_prace (obec, ulice, cislo_popisne, katastralni_uzemi) values ('Rodotópi', 'Moose', 73060, '755920');
insert into misto_prace (obec, ulice, cislo_popisne, katastralni_uzemi) values ('Cluain Meala', 'Vera', 46079, '536917');
insert into misto_prace (obec, ulice, cislo_popisne, katastralni_uzemi) values ('Kamyanyets', 'Blue Bill Park', 92653, '387378');
insert into misto_prace (obec, ulice, cislo_popisne, katastralni_uzemi) values ('Usatove', 'Saint Paul', 90114, '934345');
insert into misto_prace (obec, ulice, cislo_popisne, katastralni_uzemi) values ('Mauá', 'Basil', 15376, '331476');
insert into misto_prace (obec, ulice, cislo_popisne, katastralni_uzemi) values ('Kiel', 'Mifflin', 46650, '770257');
insert into misto_prace (obec, ulice, cislo_popisne, katastralni_uzemi) values ('Isla Pucú', 'Sage', 85199, '309191');
insert into misto_prace (obec, ulice, cislo_popisne, katastralni_uzemi) values ('Buguruslan', 'Surrey', 38048, '582001');
insert into misto_prace (obec, ulice, cislo_popisne, katastralni_uzemi) values ('Rekovac', 'American Ash', 43004, '493929');
insert into misto_prace (obec, ulice, cislo_popisne, katastralni_uzemi) values ('Santol', 'Iowa', 91140, '315165');
insert into misto_prace (obec, ulice, cislo_popisne, katastralni_uzemi) values ('Huaranchal', 'Transport', 89684, '944593');
insert into misto_prace (obec, ulice, cislo_popisne, katastralni_uzemi) values ('Serra Negra', 'Helena', 28507, '538355');
insert into misto_prace (obec, ulice, cislo_popisne, katastralni_uzemi) values ('Épernay', 'Summer Ridge', 71608, '369523');
insert into misto_prace (obec, ulice, cislo_popisne, katastralni_uzemi) values ('Changpu', 'Jackson', 46782, '697420');
insert into misto_prace (obec, ulice, cislo_popisne, katastralni_uzemi) values ('Thành Phố Thái Bình', 'Division', 49584, '756186');
insert into misto_prace (obec, ulice, cislo_popisne, katastralni_uzemi) values ('Casilda', 'Spenser', 94557, '173089');
insert into misto_prace (obec, ulice, cislo_popisne, katastralni_uzemi) values ('Roblin', 'Bartillon', 27660, '887349');
insert into misto_prace (obec, ulice, cislo_popisne, katastralni_uzemi) values ('Mīrābād', 'Vermont', 24848, '725008');
insert into misto_prace (obec, ulice, cislo_popisne, katastralni_uzemi) values ('Jiading', 'Sunnyside', 64143, '901418');

commit;